
#The function AvgSalePriceByPropertyType(property_type) 
#calculates the average sale price of properties based on the property type 

DELIMITER $$

CREATE FUNCTION AvgSalePriceByPropertyType(property_type VARCHAR(50))
RETURNS DECIMAL(15, 2)
DETERMINISTIC
BEGIN
    DECLARE avg_price DECIMAL(15, 2);
    SELECT AVG(SalePrice) INTO avg_price
    FROM properties
    WHERE LandUse = property_type;
    RETURN avg_price;
END $$

DELIMITER ;
SELECT GetAvgPriceByType('CLUB/UNION HALL/LODGE');
#provided as an input
#APARTMENT: LOW RISE (BUILT SINCE 1960)
#CHURCH
#CLUB/UNION HALL/LODGE
#CONVENIENCE MARKET WITHOUT GAS
#DAY CARE CENTER
#DORMITORY/BOARDING HOUSE
#DUPLEX
#FOREST
#GREENBELT
#GREENBELT/RES
#GRRENBELT/RES
#LIGHT MANUFACTURING
#METRO OTHER THAN OFC, SCHOOL,HOSP, OR PARK
#MOBILE HOME
#MORTUARY/CEMETERY
#NON-PROFIT CHARITABLE SERVICE
#OFFICE BLDG (ONE OR TWO STORIES)
#ONE STORY GENERAL RETAIL STORE
#PARKING LOT
#PARSONAGE
#QUADPLEX
#RESIDENTIAL COMBO/MISC
#SINGLE FAMILY
#SPLIT CLASS
#STRIP SHOPPING CENTER
#TERMINAL/DISTRIBUTION WAREHOUSE
#TRIPLEX
#VACANT COMMERCIAL LAND
#VACANT RES LAND
#VACANT RESIDENTIAL LAND
#VACANT RESIENTIAL LAND
#VACANT RURAL LAND
#VACANT ZONED MULTI FAMILY
#ZERO LOT LINE
